server:
  port: 8080

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # 应用名称
  application:
    name: blog_springboot
  # mysql配置
  datasource:
    username: root
    password: Root@123
    url: jdbc:mysql://120.78.166.194:3306/lyc_blog4?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&useSSL=false&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  druid:
    initial-size: 10
    min-idle: 10
    max-active: 150
    max-wait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    time-between-eviction-runs-millis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    min-evictable-idle-time-millis: 600000
    # 配置一个连接在池中最大生存的时间，单位是毫秒
    max-evictable-idle-time-millis: 900000
    # 配置检测连接是否有效
    validation-query: SELECT 1 FROM DUAL
    # 配置检测连接是否有效时间
    validation-query-timeout: 500
    # 在获取连接后，确定是否要进行连接空间时间的检查
    test-while-idle: true
    # 设置从连接池获取连接时是否检查连接有效性，true检查，false不检查
    test-on-borrow: false
    # 设置从连接池归还连接时是否检查连接有效性，true检查，false不检查
    test-on-return: false

  # redis配置
  redis:
    host: 120.78.166.194
    port: 6379
    # Redis服务器连接密码（默认为空）
    password:
    timeout: 100
    lettuce:
      pool:
        max-active: 150
        max-wait: 5000ms
        max-idle: 100
        min-idle: 50
  # rabbitmq配置
  rabbitmq:
    host: 120.78.166.194
    port: 5672
    username: admin
    password: mimashishenme
    listener:
      simple:
        retry:
          enabled: true
          # 重试间隔时间
          initial-interval: 3000
          # 最大重试次数
          max-attempts: 3
  # 邮箱配置
  mail:
    # 邮箱类型
    host: smtp.qq.com
    # 邮箱号
    username: yichangliu@qq.com
    # 邮箱授权码
    password: cxtkvpvsbjsycbbb

# Sa-Token 配置 (文档: https://sa-token.cc)
sa-token:
  # token名称 (同时也是cookie名称)
  token-name: Authorization
  # token前缀
  token-prefix: Bearer
  # token有效期，单位s 默认30天, -1代表永不过期
  timeout: 1800
  # token临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
  activity-timeout: -1
  # 关闭自动续签
  auto-renew: false
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  is-concurrent: true
  # token风格
  token-style: uuid
  # 在多人登录同一账号时，是否共用一个token (true共用token, 为false时每次登录新建token)
  is-share: false
  # 同一账号最大登录数量
  max-login-count: 20
  # 是否从cookie中读取token
  is-read-cookie: false
  # 是否从请求体里读取token
  is-read-body: false
  # 是否从header中读取token
  is-read-header: true
  # 是否输出操作日志
  is-log: false

# mybatisPlus配置
mybatis-plus:
  # mapper映射地址
  mapper-locations: classpath:mapper/*.xml
  # 实体类扫描包路径
  type-aliases-package: com.lyc.mapper
  configuration:
    # sql打印
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 开启驼峰命名
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      # 数据库表前缀
      table-prefix: t_

# 文件上传策略 local、cos
upload:
  strategy: local
  local:
    # nginx映射本地文件路径
    url: https://
    # 本地文件存储路径
    path: /temp/upload
  cos:
    bucket-name: bucket481282474-1316299604
    region: ap-guangzhou
    #APPID
    #appId:
    #1 初始化用户身份信息(secretId, secretKey), SecretId 是用于标识 API 调用者的身份
    secretId: AKID72lIdgaYXQCqLvLXbbOyLl14vY2ObdWR
    #SecretKey是用于加密签名字符串和服务器端验证签名字符串的密钥
    secretKey: viOvIZr0zteOExAIJE2f4ITUK7wkWBlq
    #访问路径前缀
    url: https://bucket481282474-1316299604.cos.ap-guangzhou.myqcloud.com/

# 线程池配置
thread:
  pool:
    core-pool-size: 5
    max-pool-size: 10
    queue-capacity: 50
    keep-alive-seconds: 60