server:
  port: 8080

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    username: root
    password: Root@123
    url: jdbc:mysql://192.168.48.130:3306/lyc_blog4?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&useSSL=false&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  druid:
    initial-size: 10
    min-idle: 10
    max-active: 150
    max-wait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    time-between-eviction-runs-millis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    min-evictable-idle-time-millis: 600000
    # 配置一个连接在池中最大生存的时间，单位是毫秒
    max-evictable-idle-time-millis: 900000
    # 配置检测连接是否有效
    validation-query: SELECT 1 FROM DUAL
    # 配置检测连接是否有效时间
    validation-query-timeout: 500
    # 在获取连接后，确定是否要进行连接空间时间的检查
    test-while-idle: true
    # 设置从连接池获取连接时是否检查连接有效性，true检查，false不检查
    test-on-borrow: false
    # 设置从连接池归还连接时是否检查连接有效性，true检查，false不检查
    test-on-return: false
  # redis配置
  redis:
    host: 192.168.48.130
    port: 6379
    # Redis服务器连接密码（默认为空）
    password: 123456
    timeout: 100
    lettuce:
      pool:
        max-active: 150
        max-wait: 5000ms
        max-idle: 100
        min-idle: 50
  # rabbitmq配置
  rabbitmq:
    host: 192.168.48.130
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 3000
          max-attempts: 3
  # 邮箱配置
  mail:
    # 邮箱类型
    host:
    # 邮箱号
    username:
    # 邮箱授权码
    password:

# Sa-Token 配置 (文档: https://sa-token.cc)
sa-token:
  # token名称 (同时也是cookie名称)
  token-name: Authorization
  # token前缀
  token-prefix: Bearer
  # token有效期，单位s 默认30天, -1代表永不过期
  timeout: 30000
  # token临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
  activity-timeout: 3000
  # 关闭自动续签
  auto-renew: false
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  is-concurrent: true
  token-style: uuid
  # 在多人登录同一账号时，是否共用一个token (true共用token, 为false时每次登录新建token)
  is-share: false
  # 同一账号最大登录数量
  max-login-count: 5
  # 是否从cookie中读取token
  is-read-cookie: false
  # 是否从请求体里读取token
  is-read-body: false
  # 是否从header中读取token
  is-read-header: true
  # 是否输出操作日志
  is-log: false

# mybatisPlus配置
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.lyc.mapper
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      table-prefix: t_

# 文件上传策略 local、cos、oss
upload:
  strategy: local
  local:
    # nginx映射本地文件路径
    url: https://
    path: /temp/upload
  cos:
    bucket-name:
    region:
    #APPID
    #appId:
    #1 初始化用户身份信息(secretId, secretKey), SecretId 是用于标识 API 调用者的身份
    secretId:
    #SecretKey是用于加密签名字符串和服务器端验证签名字符串的密钥
    secretKey:
    #访问路径前缀
    url:
  oss:
    endpoint:
    url:
    accessKeyId:
    accessKeySecret:
    bucketName:

# 线程池配置
thread:
  pool:
    core-pool-size: 5
    max-pool-size: 10
    queue-capacity: 50
    keep-alive-seconds: 60

# 讯飞星火
llm:
  xfxh:
    hostUrl: https://spark-api.xf-yun.com/v3.5/chat
    # 发送请求时指定的访问领域，如果是 V1.5版本 设置为 general，如果是 V2版本 设置为 generalv2
    domain: generalv3.5
    # 核采样阈值。用于决定结果随机性，取值越高随机性越强即相同的问题得到的不同答案的可能性越高。取值 [0,1]
    temperature: 0.5
    # 模型回答的tokens的最大长度，V1.5取值为[1,4096]，V2.0取值为[1,8192]。
    maxTokens: 4096
    # 大模型回复问题的最大响应时长，单位 s
    maxResponseTime: 30
    # 允许同时连接大模型的 websocket 数，如果是普通（免费）用户为 2，超过这个数连接响应会报错，具体参考官网。
    QPS: 2
    appId:
    apiKey:
    apiSecret:
